name: Docker Build and Push
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login into docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push Docker image for frontend
        uses: docker/build-push-action@v2
        with:
          context: ./userfrontend
          file:  ./userfrontend/Dockerfile
          push: true
          tags: rustaciansunny/userfrontendapp:latest

      - name: List files in backend directory
        run: ls -la ./backend

      - name: Build and push Docker image for backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: DockerFile
          push: true
          tags: rustaciansunny/myuserbackendapp:latest
